---
packages:
  - "."

# Package manager configuration
packageManager: "pnpm@8.0.0"

# Workspace settings
save-workspace-protocol: true

# Peer dependency resolution
resolution-mode: "highest"
auto-install-peers: true